### ISSUE TITLE
Server?

### ISSUE THREAD

**Issue by idkjs** [Tambourin/rent-a-bike#1]
I would like to play with this project. Is the server available somewhere?

Thank you for sharing this.

**Comment by Tambourin** [comment]
Sure, the enpoint is https://eager-parakeet-69.hasura.app/v1/graphql.
On server side GraphQL API is managed completely by Hasura cloud service. I can invite you to be a collaborator to access the service if you give your email, but there is actually not much to see. At least for simple usage this Hasura thing seems very promising as there is no need to set up resolvers.
